version: '3.8'
# O orquestrador sobe todos os serviços na mesma rede local.
# Dessa maneira não tem a necessidade de configurar IPs manualmente.
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
